language: shell

os: windows

env:
  - VERSION=5.5.3

script:
  - choco pack --version $VERSION

before_deploy:
  - choco apikey --key $CHOCO_KEY --source "https://push.chocolatey.org/"

deploy:
  skip_cleanup: true
  provider: script
  script: choco push concourse.$VERSION.nupkg
  on:
    branch: master
